"""Central configuration: env loading, benchmarks, sector mapping, thresholds.

Every tunable constant lives here so the lenses stay declarative.
"""
from __future__ import annotations

import os

from dotenv import load_dotenv

load_dotenv()

# ── Credentials / endpoints ──────────────────────────────────────────────────
SEC_USER_AGENT = os.getenv("SEC_USER_AGENT", "Equity Research HQ research@example.com")
FRED_API_KEY = os.getenv("FRED_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL", "claude-opus-4-8")

AIRTABLE_API_KEY = os.getenv("AIRTABLE_API_KEY")
AIRTABLE_BASE_ID = os.getenv("AIRTABLE_BASE_ID", "appL5ByzBTesKLEWo")

GOOGLE_SA_JSON = os.getenv("GOOGLE_SA_JSON", "./service_account.json")
GOOGLE_SHEET_ID = os.getenv("GOOGLE_SHEET_ID")

# ── Benchmarks ───────────────────────────────────────────────────────────────
BENCHMARK = "SPY"

# yfinance `.info["sector"]` value  ->  SPDR sector ETF used for relative strength
SECTOR_ETF = {
    "Technology": "XLK",
    "Energy": "XLE",
    "Financial Services": "XLF",
    "Financials": "XLF",
    "Healthcare": "XLV",
    "Consumer Cyclical": "XLY",
    "Consumer Defensive": "XLP",
    "Industrials": "XLI",
    "Utilities": "XLU",
    "Real Estate": "XLRE",
    "Basic Materials": "XLB",
    "Communication Services": "XLC",
}

# Macro lens focuses on these themes (user's areas of interest). Mapped loosely
# from sector; the web-search prompt always also keys off the actual ticker.
SECTOR_MACRO_THEME = {
    "Energy": "energy, power generation, oil & gas, grid",
    "Utilities": "electric utilities, power demand, grid build-out, data-center load",
    "Technology": "AI infrastructure, semiconductors, data centers, export controls",
    "Communication Services": "data centers, cloud, AI compute",
    "Industrials": "electrical equipment, grid & data-center build-out, tariffs",
    "Basic Materials": "critical minerals, tariffs, export controls",
}
DEFAULT_MACRO_THEME = "interest rates, tariffs, regulation relevant to the company"

# ── Markov regime thresholds ─────────────────────────────────────────────────
# Weekly total-return classification bands.
MARKOV_UP = 0.01      # weekly return >= +1%  -> "Up"
MARKOV_DOWN = -0.01   # weekly return <= -1%  -> "Down"
MARKOV_MIN_WEEKS = 200  # require ~4y of weekly data for a usable matrix
MARKOV_VOL_WINDOW = 4   # weeks, for the rolling realized-vol hi/lo tag

# ── Fundamental model assumptions ────────────────────────────────────────────
DCF_YEARS = 5
DCF_DISCOUNT_RATE = 0.085       # WACC proxy — market-realistic for quality large caps
DCF_TERMINAL_GROWTH = 0.030     # ~ long-run nominal GDP
# Bull / base / bear growth haircuts applied to the trailing FCF growth estimate.
DCF_SCENARIOS = {"bull": 1.30, "base": 1.00, "bear": 0.60}

RUNS_DIR = "runs"


def sector_etf(sector: str | None) -> str:
    """SPDR sector ETF for a yfinance sector string; falls back to the benchmark."""
    if not sector:
        return BENCHMARK
    return SECTOR_ETF.get(sector, BENCHMARK)


def macro_theme(sector: str | None) -> str:
    """Policy theme string fed to the macro web-search prompt."""
    if not sector:
        return DEFAULT_MACRO_THEME
    return SECTOR_MACRO_THEME.get(sector, DEFAULT_MACRO_THEME)


DISCLAIMER = (
    "Decision-support only — not financial advice. Generated by automated models; "
    "verify before acting."
)
